# Generated by Django 4.2.4 on 2023-08-09 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_taxes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_management', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('maintenance', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('cap_ex', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('hoa_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('landscaping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_exp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financing', models.BooleanField(default=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('gross_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('loan_term', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rehab_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacancy_rate', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('operating_expenses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_worksheet', to='home_app.operating_expenses')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(default='home_images/temp_house.png', upload_to='home_images/')),
                ('street', models.CharField(default='New Property')),
                ('city', models.CharField()),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sqft', models.PositiveBigIntegerField()),
                ('details', models.TextField()),
                ('purchase_worksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='home_app.purchase_worksheet')),
            ],
        ),
    ]
