# Generated by Django 4.2.4 on 2023-08-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='list_of_homes',
            field=models.ManyToManyField(related_name='homes', to='home_app.list_of_homes'),
        ),
    ]
