# Generated by Django 4.2.4 on 2023-08-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
        ('home_app', '0002_list_of_homes_home_list_of_homes'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='portfolio_app.portfolio'),
        ),
    ]
