# Generated by Django 4.2.4 on 2023-08-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_home_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='list_of_homes',
        ),
        migrations.RemoveField(
            model_name='home',
            name='purchase_worksheet',
        ),
        migrations.AddField(
            model_name='list_of_homes',
            name='homes',
            field=models.ManyToManyField(blank=True, related_name='list', to='home_app.home'),
        ),
        migrations.AddField(
            model_name='purchase_worksheet',
            name='home',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_worksheet', to='home_app.home'),
        ),
    ]
