# Generated by Django 4.2.4 on 2023-08-18 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists_of_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operating_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_management', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('cap_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('hoa_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('landscaping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_exp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('beds', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('baths', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.5)])),
                ('sqft', models.PositiveBigIntegerField()),
                ('details', models.TextField(blank=True, default='Property Description', null=True)),
                ('list_of_properties', models.ManyToManyField(blank=True, related_name='properties', to='property_app.list_of_properties')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='portfolio_app.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_needed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cap_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('coc', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('ltv', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('amount_financed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pricepersqft', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('arvpersqft', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('noi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loan_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_cost_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('down_payment_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('operating_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('financing', models.BooleanField(default=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('gross_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('loan_term', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rehab_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vacancy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('matching_property', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_worksheet', to='property_app.property')),
                ('operating_expenses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_worksheet', to='property_app.operating_expenses')),
                ('property_analysis', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matching_purchase_worksheet', to='property_app.property_analysis')),
            ],
        ),
    ]
