# Generated by Django 4.2.4 on 2023-08-18 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='vacancy_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
