# Generated by Django 4.2.4 on 2023-08-11 20:32

import django.core.validators
from django.db import migrations, models
import property_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_alter_operating_expenses_cap_ex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(validators=[property_app.validators.validate_state]),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
