# Generated by Django 4.2.4 on 2023-08-20 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_alter_purchase_worksheet_down_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='arv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='loan_term',
            field=models.PositiveIntegerField(blank=True, default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='vacancy_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
