# Generated by Django 4.2.4 on 2023-08-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_alter_property_state_alter_property_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
    ]
