# Generated by Django 4.2.4 on 2023-08-23 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_alter_purchase_worksheet_arv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='down_payment',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='loan_term',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='vacancy_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
