# Generated by Django 4.2.4 on 2023-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0005_alter_purchase_worksheet_down_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='loan_term',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
