# Generated by Django 4.2.4 on 2023-08-13 02:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0005_alter_property_baths_alter_property_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_flow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cap_rate', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('coc', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('ltv', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('amount_financed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricepersqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arvpersqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_cost_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='purchase_worksheet',
            name='property_analysis',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matching_purchase_worksheet', to='property_app.property_analysis'),
        ),
    ]
