# Generated by Django 4.2.4 on 2023-08-23 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0006_alter_purchase_worksheet_loan_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operating_expenses',
            name='cap_ex',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='hoa_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='insurance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='landscaping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='other_exp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='property_management',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='property_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operating_expenses',
            name='utilities',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='arv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='gross_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
