# Generated by Django 4.2.4 on 2023-08-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0006_property_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_analysis',
            name='loan_amount',
        ),
    ]
