# Generated by Django 4.2.4 on 2023-08-23 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0009_alter_operating_expenses_cap_ex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.01, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
