# Generated by Django 4.2.4 on 2023-08-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0012_alter_purchase_worksheet_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_worksheet',
            name='rehab_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
