# Generated by Django 4.2.4 on 2023-08-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0013_remove_property_city_remove_property_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='details',
            field=models.TextField(blank=True, default='Property Description', null=True),
        ),
    ]
