# Generated by Django 4.2.4 on 2023-08-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0014_alter_property_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
