# Generated by Django 4.2.4 on 2023-08-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0015_alter_property_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
    ]
