# Generated by Django 4.2.4 on 2023-08-11 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_remove_property_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.5)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
