# Generated by Django 4.2.4 on 2023-08-20 02:00

from django.db import migrations, models
import user_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user_app.validators.is_valid_email], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[user_app.validators.is_valid_password]),
        ),
    ]
